baseURL = "http://example.org/"
languageCode = "en-us"
title = "Town Hall"
theme = "town_hall_theme"
themesDir = "./themes"
phone = "0297010203"
adresse = "San Francisco, CA 94126, USA"
mail = "contact@contact.com"
maps = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2710.30842383595!2d-1.5692906840472598!3d47.21054717916056!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4805ec0450a90fc1%3A0xd5e3ee12a6f350c!2s7%20Rue%20d&#39;Alger%2C%2044000%20Nantes!5e0!3m2!1sfr!2sfr!4v1569780961058!5m2!1sfr!2sfr"


[[menu.main]]
    name =  "home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "municipal council"
    url = "/municipalCouncil"
    weight = 2
[[menu.main]]
    name = "associations"
    url = "/associations"
    weight = 3

# EVENTS AND SUBCATEGORIE FOR EVENTS 
[[ menu.main ]]
    identifier = "events"
    name = "events"
    url = "/events"
    weight = 4 

[[ menu.main]]
    parent = "events" 
    name = "All events"
    url = "/events"
    test = "grostest"
    weight = 1

[[ menu.main]]
    parent = "events" 
    name = "Upcoming events"
    url = "/events"
    weight = 2

[[ menu.main]]
    parent = "events"
    name = "Archived events"
    url = "/events"
    weight = 3

[[ menu.main]]
    parent = "events" 
    name = "Calendar events"
    url = "/events"
    weight = 4


[[ menu.footer ]]
    name = "Contact"
    url = "/contact"
    weight = 1



[params]
    homeText = "Some text for test"
    homeText2 = "Some more text"




